[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.7" }
axum-test-helper = { version = "0.4" }
tokio = { version = "1.0", features = ["full"] }
